<div class="app-main__inner">
    <div class="app-page-title app-page-title-simple">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>
                    <div class="page-title-head center-elem">
                        <span class="d-inline-block pr-2">
                            <i class="metismenu-icon pe-7s-graph2 opacity-6"></i>
                        </span>
                        <span class="d-inline-block">SMB Performance Dashboard</span>
                    </div>
                    <div class="page-title-subheading opacity-10">
                        <nav class="" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a>
                                        <i aria-hidden="true" class="metismenu-icon pe-7s-monitor"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>Dashboard Product</a>
                                </li>
                                <li class="active breadcrumb-item" aria-current="page" id="vendor-name">

                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <br/>
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon" style="width: 180px;">
                  <div class="avatar-icon-wrapper mr-3 avatar-icon-xl btn-hover-shine">
                      <div class="avatar-icon rounded" style="width:150px;height:100%;">
                          <img id="vendor-logo-" src="" alt="Avatar 5">
                      </div>
                  </div>
                </div>
                <!-- <div><span id="vendor-name-2"></span>
                    <div class="page-title-subheading">lorem ipsum.</div>
                </div> -->
            </div>
          </div>
    </div>

    <div class="tabs-animation">
        <div class="row">
          <div class="col-md-12">
              <div class="mb-3 card">
                  <div class="card-header-tab card-header">
                    <div class="card-header-title" style="padding-right: 1rem;">
                      <div class="widget-content-left">
                        <div class="d-block text-left">
                          <a href="javascript:void(0);" onclick="goback()" class="btn-wide btn-shadow btn btn-warning"><span class="lnr lnr-chevron-left"></span> </i>back</a>
                        </div>
                      </div>
                    </div>
                    <ul class="nav" style="margin-right: auto; margin-left: 0;">
                        <li class="nav-item"><a data-toggle="tab" href="#sales" class="active nav-link">Sales</a></li>
                        <!-- <li class="nav-item"><a data-toggle="tab" id="smb-product" href="#product" class="nav-link">Product</a></li> -->
                        <li hidden class="nav-item"><a data-toggle="tab" href="#dtp" class="nav-link">DTP</a></li>
                    </ul>
                    <div class="row" style="padding-right: 5rem;">
                          <h5 class="menu-header-title" id="vendor-name-1"></h5>
                    </div>

                  </div>
                  <div class="card-body">
                      <div class="tab-content">
                          <div class="tab-pane active" id="sales" role="tabpanel">
                            <div class="widget-content">
                                <div class="widget-content-wrapper">
                                    <div class="widget-content-left">
                                        <div class="widget-heading"><h5 class="d-inline-block">Sales Performance Dashboard</h5></div>
                                    </div>
                                    <div class="widget-content-right">
                                      <div class="d-block text-right">
                                          <a id="btn-detail-graphic" href="javascript:void(0);" onclick="detail('sales', true)" class="btn-wide btn-shadow btn btn-warning">Graphic Detail <span class="lnr lnr-chevron-right"></span></a>
                                          <a id="btn-back-summary" style="display:none;" href="javascript:void(0);" onclick="detail('sales', false)" class="btn-wide btn-shadow btn btn-warning"><span class="lnr lnr-chevron-left"></span> Back</a>
                                      </div>
                                    </div>
                                </div>
                            </div>
                            <div id="sales-performance">
                              <div class="row">
                              <div class="col-md-3">
                                <div class="mb-3 card">
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-md-12 col-lg-12">
                                          <div class="card mb-3 widget-content bg-warning" style="height: 117px;">
                                              <div class="widget-content-wrapper text-white">
                                                  <div class="widget-content-left">
                                                      <div class="widget-heading text-uppercase"><h3>Acquisition</h3></div>
                                                      <!-- <div class="widget-subheading">How do potential customer get to know us?</div> -->
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-md-12 col-lg-12">
                                          <div class="card mb-3 widget-content bg-success" style="height: 117px;">
                                              <div class="widget-content-wrapper text-white">
                                                  <div class="widget-content-left">
                                                      <div class="widget-heading text-uppercase"><h3>Activation</h3></div>
                                                      <!-- <div class="widget-subheading">How many potential customer will stick arround?</div> -->
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-md-12 col-lg-12">
                                          <div class="card mb-3 widget-content bg-primary" style="height: 117px;">
                                              <div class="widget-content-wrapper text-white">
                                                  <div class="widget-content-left">
                                                      <div class="widget-heading text-uppercase"><h3>Retention</h3></div>
                                                      <!-- <div class="widget-subheading">How many potential customer will stick around?</div> -->
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-md-12 col-lg-12">
                                          <div class="card mb-3 widget-content bg-danger" style="height: 117px;">
                                              <div class="widget-content-wrapper text-white">
                                                  <div class="widget-content-left">
                                                      <div class="widget-heading text-uppercase"><h3>Revenue</h3></div>
                                                      <!-- <div class="widget-subheading">How many actually become customers?</div> -->
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-md-12 col-lg-12">
                                          <div class="card mb-3 widget-content bg-info" style="height: 117px;">
                                              <div class="widget-content-wrapper text-white">
                                                  <div class="widget-content-left">
                                                      <div class="widget-heading text-uppercase"><h3>Referral</h3></div>
                                                      <!-- <div class="widget-subheading">Will those customer invite other potential customers?</div> -->
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-9">
                                <div class="mb-3 card">
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-md-12 col-lg-12">
                                        <div class="row">
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-chart widget-content-new card-btm-border card-shadow-warning border-warning card" style="height: 117px;">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant melakukan registrasi</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="">
                                                                        <!-- 2.7 <small class="opacity-5 pl-1"></small> -->
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="widget-chart-wrapper">
                                                          <div id="dashboard-sparklines-simple-3" style="min-height: 120px;">
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-content widget-content-new card-btm-border card-shadow-warning border-warning card">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant Registrasi</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="total-merchant-regis">
                                                                        2.7k <small class="opacity-5 pl-1"></small>
                                                                </div>
                                                            </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                              <div class="card mb-3 widget-content card-btm-border card-shadow-warning border-warning card" style="margin-bottom: 0px !important;height:79%">
                                                  <div class="widget-content-wrapper text-default">
                                                      <div class="widget-content-left">
                                                        <div class="widget-chat-wrapper-outer">
                                                          <div class="widget-chart-content">
                                                              <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Data User</b></div>
                                                              <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                  <div class="widget-chart-flex align-items-center" id="sign_register_user">
                                                                           <small class="opacity-5 pl-1"></small>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                        </div>
                                      </div>

                                      <div class="col-md-12 col-lg-12">
                                        <div class="row">
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-chart widget-content-new card-btm-border card-shadow-success border-success card" style="height: 117px;">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant melakukan verifikasi</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="">
                                                                        <!-- 2.7k <small class="opacity-5 pl-1"></small> -->
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="widget-chart-wrapper">
                                                          <div id="dashboard-sparklines-1" style="min-height: 120px;">
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-content widget-content-new card-btm-border card-shadow-success border-success card">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant Verifikasi</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="total-merchant-ver">
                                                                        2.7k <small class="opacity-5 pl-1"></small>
                                                                </div>
                                                            </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                              <div class="card mb-3 widget-content card-btm-border card-shadow-success border-success card" style="margin-bottom: 0px !important;height:79%">
                                                  <div class="widget-content-wrapper text-default">
                                                      <div class="widget-content-left">
                                                        <div class="widget-chat-wrapper-outer">
                                                          <div class="widget-chart-content">
                                                              <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Data Active User</b></div>
                                                              <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                  <div class="widget-chart-flex align-items-center" id="active_user">
                                                                           <small class="opacity-5 pl-1"></small>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div class="col-md-12 col-lg-12">
                                        <div class="row">
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-chart widget-content-new card-btm-border card-shadow-primary border-primary card" style="height: 117px;">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant Aktif menggunakan</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="">
                                                                        <!-- 2.7k <small class="opacity-5 pl-1"></small> -->
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="widget-chart-wrapper">
                                                          <div id="dashboard-sparklines-2" style="min-height: 120px;">
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-content widget-content-new card-btm-border card-shadow-primary border-primary card">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant transaksi</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="total-merchant-aktif">
                                                                        2.7k <small class="opacity-5 pl-1"></small>
                                                                </div>
                                                            </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                              <div class="card mb-3 widget-content card-btm-border card-shadow-primary border-primary card" style="margin-bottom: 0px !important;height:79%">
                                                  <div class="widget-content-wrapper text-default">
                                                      <div class="widget-content-left">
                                                        <div class="widget-chat-wrapper-outer">
                                                          <div class="widget-chart-content">
                                                              <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Data Transaksi</b></div>
                                                              <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                  <div class="widget-chart-flex align-items-center" id="total_traffic">
                                                                           <small class="opacity-5 pl-1"></small>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                        </div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                        </div>
                                      </div>

                                      <div class="col-md-12 col-lg-12">
                                        <div class="row">
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-chart widget-content-new card-btm-border card-shadow-danger border-danger card" style="height: 117px;">
                                              <div class="widget-content-wrapper text-default">
                                                  <div class="widget-content-left">
                                                    <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content">
                                                          <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant Berlangganan Fitur Berbayar</b></div>
                                                          <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                              <div class="widget-chart-flex align-items-center" id="">
                                                                      <!-- <span >348<span> <small class="opacity-5 pl-1">This Month</small> -->
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper">
                                                        <div id="dashboard-sparklines-4" style="min-height: 120px;">
                                                        </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                              </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-content widget-content-new card-btm-border card-shadow-danger border-danger card">
                                              <div class="widget-content-wrapper text-default">
                                                  <div class="widget-content-left">
                                                    <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content">
                                                          <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant membeli</b></div>
                                                          <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                              <div class="widget-chart-flex align-items-center" id="total-merchant-membeli">
                                                                      <!-- <span >348<span> <small class="opacity-5 pl-1">This Month</small> -->
                                                              </div>
                                                          </div>
                                                      </div>
                                                    </div>
                                                  </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>

                                      <div class="col-md-12 col-lg-12">
                                        <div class="row">
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-chart widget-content-new card-btm-border card-shadow-info border-info card" style="height: 117px;">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Merchant daftar & Merekomendasikan kepada UMKM lain</b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" >
                                                                        <!-- 540 <small class="opacity-5 pl-1">This Month</small> -->
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="widget-chart-wrapper">
                                                          <div id="dashboard-sparklines-2-1" style="min-height: 120px;">
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                          <div class="col-md-6 col-lg-4">
                                            <div class="card mb-3 widget-content widget-content-new card-btm-border card-shadow-info border-info card">
                                                <div class="widget-content-wrapper text-default">
                                                    <div class="widget-content-left">
                                                      <div class="widget-chat-wrapper-outer">
                                                        <div class="widget-chart-content">
                                                            <div class="widget-title opacity-5 text-uppercase" style="color: black;"><b>Data Teman <span id="vendor-name-2"></span></b></div>
                                                            <div class="widget-numbers mt-2 fsize-4 mb-0 w-100">
                                                                <div class="widget-chart-flex align-items-center" id="total-teman">
                                                                        <!-- 540 <small class="opacity-5 pl-1">This Month</small> -->
                                                                </div>
                                                            </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>

                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                            </div>

                            <div id="sales-performance-detail" style="display:none;">
                              <div class="row">
                                <div class="col-md-12">
                                  <div class="mb-3 card">
                                    <div class="card-header-tab card-header bg-warning">
                                      <div class="widget-chart-flex align-items-center"> Acquisition
                                      </div>
                                    </div>
                                    <div class="card-body">
                                      <div class="row">
                                        <div class="col-md-6 col-lg-6">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                <div class="widget-chart-flex align-items-center"> MERCHANT REGISTRASI
                                                </div>
                                                <div class="btn-actions-pane-right text-capitalize">
                                                  <div class="widget-chart-flex align-items-center"> 348 <small class="opacity-5 pl-1">This Month</small>
                                                  </div>
                                                </div>
                                              </div>
                                              <div class="pt-0 card-body">
                                                  <!-- <div id="chart-combined"></div> -->
                                                  <div id="chart-apex-regis"></div>
                                              </div>
                                          </div>
                                        </div>
                                        <div class="col-md-6 col-lg-6">
                                          <div class="mb-3 card">
                                            <div class="card-header-tab card-header">
                                              <div class="widget-chart-flex align-items-center"> DATA USER
                                              </div>
                                              <div class="btn-actions-pane-right text-capitalize">
                                                <div class="widget-chart-flex align-items-center"> 98 <small class="opacity-5 pl-1">This Month</small>
                                                </div>
                                              </div>
                                            </div>
                                              <div class="card-body">
                                                  <!-- <div id="chart-col-3"></div> -->
                                                  <div id="chart-apex-data-user"></div>
                                              </div>

                                          </div>
                                        </div>

                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="mb-3 card">
                                    <div class="card-header-tab card-header bg-success">
                                      <div class="widget-chart-flex align-items-center"> Activation
                                      </div>
                                    </div>
                                    <div class="card-body">
                                      <div class="row">
                                        <div class="col-md-6 col-lg-6">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                <div class="widget-chart-flex align-items-center"> MERCHANT VERIFIKASI
                                                </div>
                                                <div class="btn-actions-pane-right text-capitalize">
                                                  <div class="widget-chart-flex align-items-center"> 348 <small class="opacity-5 pl-1">This Month</small>
                                                  </div>
                                                </div>
                                              </div>
                                              <div class="pt-0 card-body">
                                                  <!-- <div id="chart-combined"></div> -->
                                                  <div id="chart-apex-ver"></div>
                                              </div>
                                          </div>
                                        </div>
                                        <div class="col-md-6 col-lg-6">
                                          <div class="mb-3 card">
                                            <div class="card-header-tab card-header">
                                              <div class="widget-chart-flex align-items-center"> DATA ACTIVE USER
                                              </div>
                                              <div class="btn-actions-pane-right text-capitalize">
                                                <div class="widget-chart-flex align-items-center"> 98 <small class="opacity-5 pl-1">This Month</small>
                                                </div>
                                              </div>
                                            </div>
                                              <div class="card-body">
                                                  <!-- <div id="chart-col-3"></div> -->
                                                  <div id="chart-apex-data-user-active"></div>
                                              </div>

                                          </div>
                                        </div>

                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="mb-3 card">
                                    <div class="card-header-tab card-header bg-primary">
                                      <div class="widget-chart-flex align-items-center"> Retention
                                      </div>
                                    </div>
                                    <div class="card-body">
                                      <div class="row">
                                        <div class="col-md-6 col-lg-6">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                <div class="widget-chart-flex align-items-center"> MERCHANT AKTIF MENGUNAKAN
                                                </div>
                                                <div class="btn-actions-pane-right text-capitalize">
                                                  <div class="widget-chart-flex align-items-center"> 348 <small class="opacity-5 pl-1">This Month</small>
                                                  </div>
                                                </div>
                                              </div>
                                              <div class="pt-0 card-body">
                                                  <!-- <div id="chart-combined"></div> -->
                                                  <div id="chart-apex-active"></div>
                                              </div>
                                          </div>
                                        </div>
                                        <div class="col-md-6 col-lg-6">
                                          <div class="mb-3 card">
                                            <div class="card-header-tab card-header">
                                              <div class="widget-chart-flex align-items-center"> DATA TRANSAKSI
                                              </div>
                                              <div class="btn-actions-pane-right text-capitalize">
                                                <div class="widget-chart-flex align-items-center"> 98 <small class="opacity-5 pl-1">This Month</small>
                                                </div>
                                              </div>
                                            </div>
                                              <div class="card-body">
                                                  <!-- <div id="chart-col-3"></div> -->
                                                  <div id="chart-apex-data-transaksi"></div>
                                              </div>

                                          </div>
                                        </div>

                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>

                          <div class="tab-pane" id="product" role="tabpanel">
                            <div class="widget-content">
                                <div class="widget-content-wrapper">
                                    <div class="widget-content-left">
                                        <div class="widget-heading"><h5 class="d-inline-block">Product Performance Dashboard</h5></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                <div class="mb-3 card">
                                  <div class="card-header-tab card-header">
                                    <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                        Platform-Based
                                    </div>
                                    <div class="btn-actions-pane-right actions-icon-btn">
                                      <div class="d-block text-right">
                                          <a href="javascript:void(0);" class="btn-wide btn-shadow btn btn-warning">Detail</a>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Total Platform Usage
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>97.5K</span>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Top Services Type
                                                  </div>
                                              </div>
                                              <div class="card-body">
                                                  <div class="widget-chart widget-chart2 text-left p-0">
                                                    <table class="align-middle text-truncate mb-0 table table-borderless table-hover">
                                                        <tbody>
                                                            <tr>
                                                                <td class="text-center" style="width: 80px;">
                                                                    <img width="35" class="rounded-circle" src="<?php $this->basePath();?>/assets/images/avatars/4.jpg" alt="">
                                                                </td>
                                                                <td class="text-center"><a href="javascript:void(0)">Client A</a></td>
                                                                <td class="text-center">
                                                                    <div class="badge badge-pill badge-danger">Ranking 1</div>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td class="text-center" style="width: 80px;">
                                                                    <img width="35" class="rounded-circle" src="<?php $this->basePath();?>/assets/images/avatars/4.jpg" alt="">
                                                                </td>
                                                                <td class="text-center"><a href="javascript:void(0)">Client B</a></td>
                                                                <td class="text-center">
                                                                    <div class="badge badge-pill badge-danger">Ranking 2</div>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td class="text-center" style="width: 80px;">
                                                                    <img width="35" class="rounded-circle" src="<?php $this->basePath();?>/assets/images/avatars/4.jpg" alt="">
                                                                </td>
                                                                <td class="text-center"><a href="javascript:void(0)">Client C</a></td>
                                                                <td class="text-center">
                                                                    <div class="badge badge-pill badge-danger">Ranking 3</div>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td class="text-center" style="width: 80px;">
                                                                    <img width="35" class="rounded-circle" src="<?php $this->basePath();?>/assets/images/avatars/4.jpg" alt="">
                                                                </td>
                                                                <td class="text-center"><a href="javascript:void(0)">Client C</a></td>
                                                                <td class="text-center">
                                                                    <div class="badge badge-pill badge-danger">Ranking 3</div>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="mb-3 card">
                                  <div class="card-header-tab card-header">
                                    <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                        Web-Based
                                    </div>
                                    <div class="btn-actions-pane-right actions-icon-btn">
                                      <div class="d-block text-right">
                                          <a href="javascript:void(0);" class="btn-wide btn-shadow btn btn-warning">Detail</a>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Latest Total Montly Activity User
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>76</span><i style="font-size:12px;"> user</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-1"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Latest Total Montly Registered User
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>54</span><i style="font-size:12px;"> user</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-2"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="mb-3 card">
                                  <div class="card-header-tab card-header">
                                    <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                        Mobile App-Based
                                    </div>
                                    <div class="btn-actions-pane-right actions-icon-btn">
                                      <div class="d-block text-right">
                                          <a href="javascript:void(0);" class="btn-wide btn-shadow btn btn-warning">Detail</a>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Latest Total Montly Activity User
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>76</span><i style="font-size:12px;"> user</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-3"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Latest Total Montly Registered User
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>54</span><i style="font-size:12px;"> user</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-4"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="mb-3 card">
                                  <div class="card-header-tab card-header">
                                    <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                        Project-Based
                                    </div>
                                    <div class="btn-actions-pane-right actions-icon-btn">
                                      <div class="d-block text-right">
                                          <a href="javascript:void(0);" class="btn-wide btn-shadow btn btn-warning">Detail</a>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Active Project
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>76</span><i style="font-size:12px;"> project</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-5"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                      <div class="col-lg-6 col-xl-4">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Project Deals
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>54</span><i style="font-size:12px;"> project</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-6"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div class="col-md-12">
                                <div class="mb-3 card">
                                  <div class="card-header-tab card-header">
                                    <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                        Service Based
                                    </div>
                                    <div class="btn-actions-pane-right actions-icon-btn">
                                      <div class="d-block text-right">
                                          <a href="javascript:void(0);" class="btn-wide btn-shadow btn btn-warning">Detail</a>
                                      </div>
                                    </div>
                                  </div>
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-lg-12 col-xl-12">
                                          <div class="mb-3 card">
                                              <div class="card-header-tab card-header">
                                                  <div class="card-header-title font-size-lg text-capitalize font-weight-normal">
                                                      <i class="header-icon lnr-laptop-phone mr-3 text-muted opacity-6"> </i>Client per service
                                                  </div>
                                              </div>
                                              <div class="widget-chart widget-chart2 text-left p-0">
                                                  <div class="widget-chat-wrapper-outer">
                                                      <div class="widget-chart-content widget-chart-content-lg">
                                                          <div class="widget-numbers">
                                                              <div class="widget-chart-flex">
                                                                  <div>
                                                                      <span class="opacity-10 text-warning pr-2">
                                                                          <i class="fa fa-dot-circle"></i>
                                                                      </span>
                                                                      <span>76</span><i style="font-size:12px;"> Client</i>
                                                                  </div>
                                                              </div>
                                                          </div>
                                                      </div>
                                                      <div class="widget-chart-wrapper widget-chart-wrapper-xlg opacity-10 m-0">
                                                          <div id="dashboard-sparkline-2-7"></div>
                                                      </div>
                                                  </div>
                                              </div>
                                          </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div class="tab-pane" id="dtp" role="tabpanel">
                            <div class="widget-content">
                                <div class="widget-content-wrapper">
                                    <div class="widget-content-left">
                                        <div class="widget-heading"><h5 class="d-inline-block">DTP Performance Dashboard</h5></div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                              <div class="col-md-12">
                                <div class="mb-3 card bg-dark">
                                  <div class="card-body">
                                    <div class="row">
                                      <div class="col-lg-4 col-xl-4">
                                        <div class="card mb-3 widget-content bg-dtp">
                                            <div class="widget-content-wrapper text-white">
                                                <div class="widget-content-left">
                                                    <div class="widget-subheading">Total Page Views</div>
                                                    <div class="widget-heading">Users</div>
                                                </div>
                                                <div class="widget-content-right">
                                                    <div class="widget-numbers text-white"><span>984</span><span style="font-size:12px;"> /month</span></div>
                                                </div>
                                            </div>
                                        </div>
                                      </div>
                                      <div class="col-lg-4 col-xl-4">
                                        <div class="card mb-3 widget-content bg-dtp">
                                            <div class="widget-content-wrapper text-white">
                                                <div class="widget-content-left">
                                                    <div class="widget-subheading">Total Site Traffic</div>
                                                    <div class="widget-heading">Page Views</div>
                                                </div>
                                                <div class="widget-content-right">
                                                    <div class="widget-numbers text-white"><span>7,605</span></div>
                                                </div>
                                            </div>
                                        </div>
                                      </div>
                                      <div class="col-lg-4 col-xl-4">
                                        <div class="card mb-3 widget-content bg-dtp">
                                            <div class="widget-content-wrapper text-white">
                                                <div class="widget-content-left">
                                                    <div class="widget-heading">Event per ession</div>
                                                </div>
                                                <div class="widget-content-right">
                                                    <div class="widget-numbers text-white"><span>1.247</span></div>
                                                </div>
                                            </div>
                                        </div>
                                      </div>
                                      <div class="col-lg-12 col-xl-12">
                                        <div class="mb-3 card bg-dtp">
                                            <div class="card-header-tab card-header" style="background: rgb(255 255 255 / 0%);">
                                                <div class="card-header-title font-size-lg text-capitalize font-weight-normal">Page Views
                                                </div>
                                            </div>
                                            <div class="pt-0 card-body">
                                                <div id="chart-combined"></div>
                                            </div>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
        </div>
    </div>
</div>

</div>
