<div class="app-main__inner">
    <div class="app-page-title app-page-title-simple">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>
                    <div class="page-title-head center-elem">
                        <span class="d-inline-block pr-2">
                            <i class="metismenu-icon pe-7s-graph2 opacity-6"></i>
                        </span>
                        <span class="d-inline-block">SMB Performance Dashboard</span>
                    </div>
                    <div class="page-title-subheading opacity-10">
                        <nav class="" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a>
                                        <i aria-hidden="true" class="metismenu-icon pe-7s-monitor"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>Dashboard Product</a>
                                </li>

                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="mbg-3 alert alert-info alert-dismissible fade show" role="alert">
        <span class="pr-2">
            <i class="fa fa-question-circle"></i>
        </span>
        This dashboard example was created using only the available elements and components, no additional SCSS was
        written!
    </div> -->

    <div class="tabs-animation">
        <div class="row" id="for-content">
          <div class="col-sm-12 col-md-3 col-xl-3">
              <div class="card-shadow-primary card-border mb-3 profile-responsive card">
                <div class="dropdown-menu-header">
                    <div class="dropdown-menu-header-inner bg-dark">
                        <div class="menu-header-content">
                            <div class="avatar-icon-wrapper mb-3 avatar-icon-xl">
                                <div class="avatar-icon">
                                    <img src="<?php $this->basePath();?>/assets/images/avatars/6.jpg" alt="Avatar 5">
                                </div>
                            </div>
                            <div>
                                <h5 class="menu-header-title">QCA</h5>
                            </div>
                        </div>
                    </div>
                </div>
                  <ul class="list-group list-group-flush">
                      <li class="p-0 list-group-item">
                          <div class="widget-content">
                              <div class="text-center">
                                  <h5 class="widget-heading mb-0 opacity-4">Aenean commodo ligula eget dolor.
                                      Aenean massa. Cum sociis natoque.</h5>
                              </div>
                          </div>
                      </li>
                      <li class="p-0 list-group-item">
                          <div class="grid-menu grid-menu-2col">
                              <div class="no-gutters row">
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button onclick="parent.openDetailVisit('QCA')" class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-chart-bars text-warning opacity-7 btn-icon-wrapper mb-2"></i>Visit
                                          </button>
                                      </div>
                                  </div>
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-license text-warning opacity-7 btn-icon-wrapper mb-2"></i>View
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-sm-12 col-md-3 col-xl-3">
              <div class="card-shadow-primary card-border mb-3 profile-responsive card">
                <div class="dropdown-menu-header">
                    <div class="dropdown-menu-header-inner bg-dark">
                        <div class="menu-header-content">
                            <div class="avatar-icon-wrapper mb-3 avatar-icon-xl">
                                <div class="avatar-icon">
                                    <img src="<?php $this->basePath();?>/assets/images/avatars/6.jpg" alt="Avatar 5">
                                </div>
                            </div>
                            <div>
                                <h5 class="menu-header-title">QCA</h5>
                            </div>
                        </div>
                    </div>
                </div>
                  <ul class="list-group list-group-flush">
                      <li class="p-0 list-group-item">
                          <div class="widget-content">
                              <div class="text-center">
                                  <h5 class="widget-heading mb-0 opacity-4">Aenean commodo ligula eget dolor.
                                      Aenean massa. Cum sociis natoque.</h5>
                              </div>
                          </div>
                      </li>
                      <li class="p-0 list-group-item">
                          <div class="grid-menu grid-menu-2col">
                              <div class="no-gutters row">
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-chart-bars text-warning opacity-7 btn-icon-wrapper mb-2"></i>Visit
                                          </button>
                                      </div>
                                  </div>
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-license text-warning opacity-7 btn-icon-wrapper mb-2"></i>View
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-sm-12 col-md-3 col-xl-3">
              <div class="card-shadow-primary card-border mb-3 profile-responsive card">
                <div class="dropdown-menu-header">
                    <div class="dropdown-menu-header-inner bg-dark">
                        <div class="menu-header-content">
                            <div class="avatar-icon-wrapper mb-3 avatar-icon-xl">
                                <div class="avatar-icon">
                                    <img src="<?php $this->basePath();?>/assets/images/avatars/6.jpg" alt="Avatar 5">
                                </div>
                            </div>
                            <div>
                                <h5 class="menu-header-title">QCA</h5>
                            </div>
                        </div>
                    </div>
                </div>
                  <ul class="list-group list-group-flush">
                      <li class="p-0 list-group-item">
                          <div class="widget-content">
                              <div class="text-center">
                                  <h5 class="widget-heading mb-0 opacity-4">Aenean commodo ligula eget dolor.
                                      Aenean massa. Cum sociis natoque.</h5>
                              </div>
                          </div>
                      </li>
                      <li class="p-0 list-group-item">
                          <div class="grid-menu grid-menu-2col">
                              <div class="no-gutters row">
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-chart-bars text-warning opacity-7 btn-icon-wrapper mb-2"></i>Visit
                                          </button>
                                      </div>
                                  </div>
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-license text-warning opacity-7 btn-icon-wrapper mb-2"></i>View
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="col-sm-12 col-md-3 col-xl-3">
              <div class="card-shadow-primary card-border mb-3 profile-responsive card">
                <div class="dropdown-menu-header">
                    <div class="dropdown-menu-header-inner bg-dark">
                        <div class="menu-header-content">
                            <div class="avatar-icon-wrapper mb-3 avatar-icon-xl">
                                <div class="avatar-icon">
                                    <img src="<?php $this->basePath();?>/assets/images/avatars/6.jpg" alt="Avatar 5">
                                </div>
                            </div>
                            <div>
                                <h5 class="menu-header-title">QCA</h5>
                            </div>
                        </div>
                    </div>
                </div>
                  <ul class="list-group list-group-flush">
                      <li class="p-0 list-group-item">
                          <div class="widget-content">
                              <div class="text-center">
                                  <h5 class="widget-heading mb-0 opacity-4">Aenean commodo ligula eget dolor.
                                      Aenean massa. Cum sociis natoque.</h5>
                              </div>
                          </div>
                      </li>
                      <li class="p-0 list-group-item">
                          <div class="grid-menu grid-menu-2col">
                              <div class="no-gutters row">
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-chart-bars text-warning opacity-7 btn-icon-wrapper mb-2"></i>Visit
                                          </button>
                                      </div>
                                  </div>
                                  <div class="col-sm-6">
                                      <div class="p-1">
                                          <button class="btn-icon-vertical btn-transition-text btn-transition btn-transition-alt pt-2 pb-2 btn btn-outline-warning"><i
                                                  class="lnr-license text-warning opacity-7 btn-icon-wrapper mb-2"></i>View
                                          </button>
                                      </div>
                                  </div>
                              </div>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
        </div>
    </div>
</div>

</div>
