<div class="app-main__inner">
    <div class="app-page-title app-page-title-simple">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>
                    <div class="page-title-head center-elem">
                        <span class="d-inline-block pr-2">
                            <i class="metismenu-icon pe-7s-graph2 opacity-6"></i>
                        </span>
                        <span class="d-inline-block">SMB Performance Dashboard</span>
                    </div>
                    <div class="page-title-subheading opacity-10">
                        <nav class="" aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">
                                    <a>
                                        <i aria-hidden="true" class="metismenu-icon pe-7s-users"></i>
                                    </a>
                                </li>
                                <li class="breadcrumb-item">
                                    <a>Users Management</a>
                                </li>
                                <li class="breadcrumb-item" aria-current="page">
                                    <a>List Users</a>
                                </li>

                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="mbg-3 alert alert-info alert-dismissible fade show" role="alert">
        <span class="pr-2">
            <i class="fa fa-question-circle"></i>
        </span>
        This dashboard example was created using only the available elements and components, no additional SCSS was
        written!
    </div> -->

    <div class="tabs-animation">
      <div class="main-card mb-3 card">
          <div class="card-body">
              <div class="d-inline-block dropdown">
                    <button type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="btn-shadow dropdown-toggle btn btn-info">
                        <span class="btn-icon-wrapper pr-2 opacity-7">
                            <i class="fa fa-plus fa-w-20"></i>
                        </span>
                        Add
                    </button>
                    <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="modal" data-target="#modal_new_user">
                                    <i class="nav-link-icon lnr-user"></i>
                                    <span> New User </span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
              <table style="width: 100%;" id="list-users" class="table table-hover table-striped table-bordered">
                  <thead>
                  <tr>
                      <th>NO</th>
                      <th>USERNAME</th>
                      <th>NAME</th>
                      <th>ROLE</th>
                      <th>STATUS</th>
                      <th>DATE</th>
                      <th>ACTION</th>
                  </tr>
                  </thead>
              </table>
          </div>
      </div>
    </div>
</div>

</div>
