<style>

    input[type="text"] {
        display: block;
        width: 100%;
        height: 36px;
        padding: 7px 12px;
        font-size: 13px;
        line-height: 1.5384616;
        color: #333333;
        background-color: #fff;
        background-image: none;
        border: 1px solid #0fbdbc;
        border-top: 0px;
        border-left: 0px;
        border-right: 0px;
        border-radius: 0px;
    }

    .btn-success {
        color: #fff;
        background-color: #009688;
        border-color: #0fbfbf;
    }

    .stepy-header {
        list-style: none;
        padding: 0;
        margin: 0;
        display: table;
        table-layout: fixed;
        width: 100%;
        display: none;
    }

</style>

<div class="page-container">

    <div class="content-wrapper">
        <div class="container contentx">
            <div class ="content" >
                <div class="content-group"  style="box-shadow: -16px 19px 15px 0px #c1adad8c;">
                    <div class="page-header page-header-default has-cover" id="thisHeader" style="border: 1px solid #ddd; border-bottom: 0;height: 160px;display:none;">
                        <div class="page-header-content">
                            <div class="page-title">
                                <h5>
                                    <!-- <i class="icon-arrow-left52 position-left"></i> -->
                                    <span class="text-semibold"><span id="thisJudul"></span></span> 
                                    <small class="display-block"><span id="thisDeskripsi" style="line-height: 1.4;"></span></small>
                                </h5>
                            <a class="heading-elements-toggle"><i class="icon-more"></i></a></div>

                            <!-- <div class="heading-elements">
                                <button class="btn btn-link btn-icon btn-sm heading-btn legitRipple"><i class="icon-gear"></i></button>
                            </div> -->
                        </div>

                    </div>
                </div>
                    
                <!-- Sales stats -->
                <div class="panel panel-flat " style="    box-shadow: -16px 19px 15px 0px #c1adad8c;">
                <!-- <iframe src="http://itb_quick.dan/content/nikanschsweish/V3BibzRmU01FWW0xWEtDYXNNRGhXQT09" width="100%" title="W3Schools Free Online Web Tutorials"></iframe> -->
                
                    <!-- <div class="panel-heading">
                        <h6 class="panel-title">User Online/Offline</h6>
                    </div> -->

                    <div class="panel-body">
                        <span class="wixard"></span>
                        <textarea class ="form-control" id="jsonArea" style="display:none;"></textarea>

                            <!-- <form>
                                <span class="renderForm"></span>
                                <span class="btn btn-danger pull-right" id="InsertPolay" style="background-color: #ff004e; font-weight: 600; border-color: #ff004e;">
                                    <i class="icon-wave2"></i> Kirim Formulir
                                </span>                                
                            </form> -->
                
                    </div>
                <!-- /sales stats -->

                </div>
            
            </div>
        </div>

    </div>
</div>
