<style>

    .form-control {
        display: block;
        width: 100%;
        height: 36px;
        padding: 7px 12px;
        font-size: 13px;
        line-height: 1.5384616;
        color: #333333;
        background-color: #fff;
        background-image: none;
        border: 1px solid #0fbdbc;
        border-top: 0px;
        border-left: 0px;
        border-right: 0px;
        border-radius: 0px;
    }

    .btn-success {
        color: #fff;
        background-color: #009688;
        border-color: #0fbfbf;
    }

    .input-group-addon:first-child {
        border-right: 0;
        border-left: 0;
        border-top: 0;
        border-color: #ffffff;
    }
</style>

<div class="page-container">
    <div class="content-wrapper">
        		<!-- Page header -->
				<div class="page-header page-header-default">
					

					<div class="breadcrumb-line">
						<ul class="breadcrumb">
							<li><a href="/content/dashboardtu"><i class="icon-home2 position-left"></i> Home</a></li>
							<li class="active">Setting Jadwal</li>
						</ul>

						<ul class="breadcrumb-elements">
							<li><a href="#"><i class="icon-comment-discussion position-left"></i> Support</a></li>
							<li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown">
									<i class="icon-gear position-left"></i>
									Settings
									<span class="caret"></span>
								</a>

								<ul class="dropdown-menu dropdown-menu-right">
									<li><a href="#"><i class="icon-user-lock"></i> Account security</a></li>
									<li><a href="#"><i class="icon-statistics"></i> Analytics</a></li>
									<li><a href="#"><i class="icon-accessibility"></i> Accessibility</a></li>
									<li class="divider"></li>
									<li><a href="#"><i class="icon-gear"></i> All settings</a></li>
								</ul>
							</li>
						</ul>
					</div>
				</div>
				<!-- /page header -->

        <!-- Content area -->
		<div class="content">

        </div>
    </div>
</div>