<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<?= $this->doctype() ?>

<?php
  $csrf = '';
  if (!empty($_SESSION['__KHANSIA'])) {
    $csrf = $_SESSION['__KHANSIA']['csrf_token'];
  }
?>

<!DOCTYPE html>
<html  lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Language" content="en">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="csrf-token" content="<?= $csrf ?>">
    <?= $this->headTitle('Minimal Dashboard - Examples of just how powerful ArchitectUI really is!')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <meta name="msapplication-tap-highlight" content="no">

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .'/img/titlelogo.png']) ?>

    <link href="<?php $this->basePath();?>/assets/css/main.css" rel="stylesheet"></head>

    <script src="<?php $this->basePath();?>/assets/scripts/jquery-3.4.1.min.js"></script>

    <script type="text/javascript" src="<?php $this->basePath();?> /action-js/global-js/crypto.js"></script>

</head>
<style>

  body{
    overflow:hidden;
  }

  .widget-content {
    padding: 1.47rem;
  }
  .widget-content-new {
    padding: 1.2rem!important;
  }
  .bg-dtp {
    background-color: #58626b;
  }

</style>
<body>
<div class="app-theme-gray body-tabs-shadow fixed-header fixed-sidebar">
  <div class="app-main__outer">
    <div class="app-main__inner">

      <?php echo $this->content;?>

    </div>
  </div>
</div>

  <?= $this->headScript()->prependFile($this->basePath('/assets/scripts/main.js')) ?>

  <?= $this->inlineScript() ?>
</body>
</html>
