<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>

<?= $this->doctype() ?>

<?php
  $csrf = '';
  if (!empty($_SESSION['__KHANSIA'])) {
    $csrf = $_SESSION['__KHANSIA']['csrf_token'];
  }
?>

<!DOCTYPE html>
<html  lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta http-equiv="Content-Language" content="en">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="csrf-token" content="<?= $csrf ?>">
    <?= $this->headTitle('Minimal Dashboard - Examples of just how powerful ArchitectUI really is!')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <meta name="msapplication-tap-highlight" content="no">

    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() .'/img/titlelogo.png']) ?>

    <link href="<?php $this->basePath();?>/assets/css/main.css" rel="stylesheet"></head>
    <link href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" rel="stylesheet">

    <script src="<?php $this->basePath();?>/assets/scripts/jquery-3.4.1.min.js"></script>

    <script type="text/javascript" src="<?php $this->basePath();?> /action-js/global-js/crypto.js"></script>

</head>
<style>

  body{
    overflow:hidden;
  }

  .widget-content {
    padding: 1.47rem;
  }
  .widget-content-new {
    padding: 1.2rem!important;
  }
  .bg-dtp {
    background-color: #58626b;
  }

</style>
<body>
<div class="app-theme-gray body-tabs-shadow fixed-header fixed-sidebar">
  <div class="app-main__outer">
    <div class="app-main__inner">

      <?php echo $this->content;?>

    </div>
  </div>
</div>

<div class="modal fade" id="modal_new_user" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-xs" role="document">
              <div class="modal-content">
                  <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLabel">New User Login</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                  <div class="modal-body">
                        <!-- <h5 class="card-title">Grid Rows</h5> -->
                        <input type="hidden" id="id_kalib">
                            <div class="form-row">
                                <div class="col-md-12">
                                  <div class="position-relative form-group">
                                    <label class="card-title">Name</label>
                                    <input id="is_name" name="state" type="text" class="form-control">
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="position-relative form-group">
                                    <label class="card-title">Username</label>
                                    <input id="is_uname" name="state" type="text" class="form-control">
                                  </div>
                                </div>
                                <div class="col-md-12">
                                  <div class="position-relative form-group">
                                    <label class="card-title">Role</label>
                                    <select id="is_role" class="form-control">
                                      <option value="0">-Pilih-</option>
                                      <option value="10">Super Admin</option>
                                      <option value="20">Admin</option>
                                      <option value="30">User</option>
                                    </select>
                                  </div>
                                </div>
                            </div>
                  </div>
                  <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">close</button>
                      <button type="button" class="btn btn-primary" id="add-user" target="_blank">Save</button>
                  </div>
              </div>
          </div>
        </div>

  <?= $this->headScript()->prependFile($this->basePath('/assets/scripts/main.js')) ?>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script></body>

  <?= $this->inlineScript() ?>
</body>
</html>
