<style>

    .jumbotron {
        border-radius: 0;
        background-repeat: no-repeat;
        -webkit-background-size: cover;
        background-size: cover;
        background-position: 50% 50%;
    }

    .lead-box {
        padding: 5rem;
        background-color: #e9ecef;
        opacity: .7;
    }

    .jumbotron-home-page {
        background-image: url(../img/home-page.jpg);
    }

    .text-primary {
        color: #013755 !important;
        font-weight: 300 !important;
    }

    .h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6 {
        margin-bottom: .5rem !important;
        font-weight: 300 !important;
        line-height: 1.2 !important;
    }

    .h1, h1 {
        font-size: 4.5rem !important;
        font-weight: 300 !important;
    }

    body {
        padding-top: 98px;    
        font-family: sans-serif;
        line-height: 1.8rem;
        letter-spacing: .5px;
    }

</style>

<div class="jumbotron jumbotron-home-page text-center">
    <div class="lead-box" style="    margin-top: 50px;">
        <h1 class="text-primary"> Khansia  Project, the enterprise-ready PHP Framework and components</h1>

        <h2 class="text-primary">
            A community-supported, open source continuation of Zend Framework.
        </h2>
    </div>
</div>

<div class="container">
    <div class="row row-cols-1 row-cols-md-3">
        <div class="col-md-4">
            <div class="card h-100 border border-components rounded">
                <div class="card-header bg-components text-white w-auto">
                    Components and MVC
                </div>

                <div class="card-body">
                    <h5 class="card-title">Enterprise-ready PHP components and MVC framework</h5>

                    <p class="card-text">
                        Components for any PHP application, including dependency injection,
                        event dispatchers, input validation and filtering, pagination and
                        navigation, feed generation and parsing, and much, much more.
                    </p>

                    <p class="card-text">
                        A standards-based, event-driven MVC framework with a flexible workflow.
                    </p>

                    <a class="btn btn-components" href="https://docs.laminas.dev">
                        Laminas documentation
                    </a>
                </div>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-expressive rounded">
                <div class="card-header bg-expressive text-white">
                    Mezzio
                </div>

                <div class="card-body">
                    <h5 class="card-title">PHP Middleware in Minutes</h5>

                    <p class="card-text">
                        Build PHP middleware applications, using the
                        PSR-7 (HTTP Messages) and PSR-15 (HTTP Request Handlers)
                        specifications, using a variety of routing and
                        templating options, and the dependency injection
                        container you prefer.
                    </p>

                    <a class="btn btn-expressive" href="https://docs.mezzio.dev">
                        Mezzio documentation
                    </a>
                </div>
            </div>
        </div>

        <div class="col mb-4">
            <div class="card h-100 border border-apigility rounded">
                <div class="card-header bg-apigility text-white">
                    API Tools
                </div>

                <div class="card-body">
                    <h5 class="card-title">Build Beautiful RESTful APIs</h5>

                    <p class="card-text">
                        Build RESTful APIs using standards such as Hypertext
                        Application Language and Problem Details for HTTP APIs,
                        and provide validation, authentication, authorization,
                        and versioning right out of the box!
                    </p>

                    <a class="btn btn-apigility" href="https://api-tools.getlaminas.org">
                        API Tools documentation
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>